"""Каталог реальных моделей точек доступа."""

AP_CATALOG = [
    {"vendor": "Cisco", "model": "Aironet 2800i",
     "standard": "802.11ac Wave 2", "band": "2.4/5",
     "max_clients": 100, "tx_power_dbm": 23, "antenna_gain": 6,
     "throughput_mbps": 800, "description": "Внутренняя точка доступа"},
    {"vendor": "Cisco", "model": "Catalyst 9130AXI",
     "standard": "802.11ax (Wi-Fi 6)", "band": "2.4/5",
     "max_clients": 200, "tx_power_dbm": 23, "antenna_gain": 6,
     "throughput_mbps": 1500, "description": "Wi-Fi 6, MU-MIMO 4x4"},
    {"vendor": "Cisco", "model": "Catalyst 9166I",
     "standard": "802.11ax (Wi-Fi 6E)", "band": "2.4/5/6",
     "max_clients": 400, "tx_power_dbm": 24, "antenna_gain": 7,
     "throughput_mbps": 3900, "description": "Wi-Fi 6E, трёхдиапазонная"},
    {"vendor": "Ubiquiti", "model": "UniFi U6 Pro",
     "standard": "802.11ax (Wi-Fi 6)", "band": "2.4/5",
     "max_clients": 300, "tx_power_dbm": 22, "antenna_gain": 6,
     "throughput_mbps": 2400, "description": "Wi-Fi 6, 4x4 MU-MIMO"},
    {"vendor": "Ubiquiti", "model": "UniFi U6 Enterprise",
     "standard": "802.11ax (Wi-Fi 6E)", "band": "2.4/5/6",
     "max_clients": 600, "tx_power_dbm": 24, "antenna_gain": 7,
     "throughput_mbps": 4800, "description": "Wi-Fi 6E, до 600 клиентов"},
    {"vendor": "Ubiquiti", "model": "UniFi AC Lite",
     "standard": "802.11ac", "band": "2.4/5",
     "max_clients": 100, "tx_power_dbm": 20, "antenna_gain": 3,
     "throughput_mbps": 867, "description": "Бюджетная Wi-Fi 5"},
    {"vendor": "TP-Link", "model": "EAP660 HD",
     "standard": "802.11ax (Wi-Fi 6)", "band": "2.4/5",
     "max_clients": 200, "tx_power_dbm": 23, "antenna_gain": 6,
     "throughput_mbps": 3600, "description": "Wi-Fi 6, 4x4 MU-MIMO"},
    {"vendor": "TP-Link", "model": "EAP245",
     "standard": "802.11ac Wave 2", "band": "2.4/5",
     "max_clients": 100, "tx_power_dbm": 20, "antenna_gain": 5,
     "throughput_mbps": 1300, "description": "Wi-Fi 5, 3x3 MU-MIMO"},
    {"vendor": "MikroTik", "model": "cAP ac",
     "standard": "802.11ac", "band": "2.4/5",
     "max_clients": 60, "tx_power_dbm": 20, "antenna_gain": 4,
     "throughput_mbps": 867, "description": "Компактная"},
    {"vendor": "MikroTik", "model": "hAP ac³",
     "standard": "802.11ac", "band": "2.4/5",
     "max_clients": 80, "tx_power_dbm": 20, "antenna_gain": 5,
     "throughput_mbps": 1200, "description": "С интегрированным контроллером"},
    {"vendor": "Huawei", "model": "AirEngine 5760-22W",
     "standard": "802.11ax (Wi-Fi 6)", "band": "2.4/5",
     "max_clients": 250, "tx_power_dbm": 23, "antenna_gain": 6,
     "throughput_mbps": 3000, "description": "Wi-Fi 6, 4x4 MU-MIMO"},
    {"vendor": "Eltex", "model": "WEP-3ax",
     "standard": "802.11ax (Wi-Fi 6)", "band": "2.4/5",
     "max_clients": 200, "tx_power_dbm": 20, "antenna_gain": 5,
     "throughput_mbps": 1800, "description": "Отечественная Wi-Fi 6"},
    {"vendor": "Generic", "model": "Generic AP",
     "standard": "802.11ac", "band": "5",
     "max_clients": 50, "tx_power_dbm": 20, "antenna_gain": 6,
     "throughput_mbps": 400, "description": "Универсальный профиль"},
]